version: '3.3'
services:
  ubuntu:
    container_name: ubuntu-server
    build:
      context: .
      dockerfile: ./dockerfiles/ubuntu-server.dockerfile
      args:
        SSH_MASTER_USER: ${SSH_MASTER_USER}
        SSH_MASTER_PASS: ${SSH_MASTER_PASS}
    ports:
      - "2220:22"

  centos:
    container_name: centos-server
    build:
      context: .
      dockerfile: ./dockerfiles/centos-server.dockerfile
      args:
        SSH_MASTER_USER: ${SSH_MASTER_USER}
        SSH_MASTER_PASS: ${SSH_MASTER_PASS}
    ports:
      - "2221:22"
